name: ShellCheck
on: [push, pull_request]
jobs:
  shell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: bash check_sh.sh
        run: |
          ./check_sh.sh

      - name: Run shfmt
        run: |
          bash run_shfmt.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
